config/routes.rb
Flix::Application.routes.draw do


  

  # devise_for :users do 
  # get '/users/sign_out' => 'devise/sessions#destroy', 
  # 	controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" } do


  get "info/contact"
  get "info/about"
  get "info/landing"
  get "info/test"
  get '/users/sign_out' => 'devise/sessions#destroy'

  root "info#landing"
end

  resources :events do
     resources :registrations
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

  validates :name, :location, presence: true

  validates :description, length: {minimum: 2}

  validates :price, numericality: { greater_that_or_equal_to: 0}

  validates :capacity, numericality: {only_integer: true, greater_than: 0}

  validates :image_file_name, allow_blank: true, format: {
    with: /\w+\.(gif|jpg|png)\z/i,
    message: "Sorry, Must be a GIF, JPG, or PNG only."
  }

  has_many :registrations, dependent: :destroy

  def free?
    price.blank? || price == 0
  end

  def self.upcoming
    where("starts_at >= ?", Time.now).order("starts_at")
  end

  def spots_left
    capacity - registrations.size
  end

  def sold_out?
    spots_left.zero?
  end


end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
end

app/models/registration.rb
class Registration < ActiveRecord::Base

  validates :name, presence: true
  validates :email, format: { with: /(\S+)@(\S+)/ }

  HOW_HEARD_OPTIONS = [
    'Facebook',
    'Twitter',
    'Search Engine',
    'Friend/CoWorker',
    'Other'
  ]

  validates :how_heard,
            inclusion: { in: HOW_HEARD_OPTIONS }

  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
    def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
 	user = User.where(:provider => auth.provider, :uid => auth.uid).first
  if user
    return user
  else
    registered_user = User.where(:email => auth.uid + "@twitter.com").first
    if registered_user
      return registered_user
    else
      user = User.create(name:auth.info.name,
        provider:auth.provider,
        uid:auth.uid,
        email:auth.uid+"@twitter.com",
        password:Devise.friendly_token[0,20],
      )
    end
  end
end  

   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :authenticate_user!, except: [:index, :contact, :about, :landing, :test]

  protect_from_forgery with: :exception

  def after_sign_out_path_for(user)
    events_path
  end

  def after_sign_in_path_for(user)
    events_path
  end



end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.upcoming
  end

  def name
    @events = Event.name
  end

  def all
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    event_params = params.require(:event).
          permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)

    if @event.update(event_params)
      flash[:notice] = "Event successfully updated!"
      redirect_to @event
    else
    render :edit
    end
  end

  def new
    @event = Event.new
  end

  def create
    event_params = params.require(:event).
          permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end

private

  def event_params
    params.require(:event).
    permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
  end


end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def contact
  end

  def about
  end

  def landing
    render :layout => false
  end

  def test
    render :layout => false
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_event

  def index
    @registrations = @event.registrations
  end

  def new
    @registration = @event.registrations.new
  end

  def create
    @registration = @event.registrations.new(registration_params)
    if @registration.save
      redirect_to event_registrations_path(@event),
        notice: "Thanks for registering!"
    else
      render :new
    end
  end

private

  def registration_params
    params.require(:registration).permit(:name, :email, :how_heard)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	
  def twitter
    auth = env["omniauth.auth"]
    #Rails.logger.info("auth is **************** #{auth.to_yaml}")
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"],current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_uid"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def format_price(event)
    if event.free?
      content_tag(:strong, "Free!")
    else
      number_to_currency(event.price)
    end
  end

  def image_for(event)
    if event.image_file_name.blank?
      image_tag 'calendar1.png'
    else
    image_tag event.image_file_name
    end
  end

end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
  def register_link_for(event)
    if event.sold_out?
      #content_tag(:strong, "This Event is Sold Out.")
      image_tag("soldout1.png")
    else
      hint = content_tag(:span, "Only #{pluralize(event.spots_left, 'spot')} left!", class: 'scarcity')
      link_to "Register! #{hint}".html_safe, new_event_registration_path(event), class: 'button ok register'
    end
  end
end

app/views/Shared/_errors.html.erb
<% if @event.errors.any? %>
    <header>
      <h2>
        Oops! Your form could not be saved.
      </h2>
      <h3>
      Please correct the following
      <%= pluralize(@event.errors.count, "error") %>:
      </h3>
    </header>
    <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
<% end %>

app/views/Shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <p>
    <%= f.label :name, title: "Enter Your Information", data: {tooltip: true}  %><br/>
    <%= f.text_field :name, autofocus: true %>
  </p>
  <p>
    <%= f.label :description, title: "Enter Your Information", data: {tooltip: true} %><br/>
    <%= f.text_area :description, cols: 40, rows: 7 %>
  </p>
  <p>
    <%= f.label :location, title: "Enter Your Information", data: {tooltip: true} %><br/>
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.label :price, title: "Enter Your Information", data: {tooltip: true} %><br/>
    <%= f.number_field :price %>
  </p>
  <p>
    <%= f.label :starts_at, title: "Enter Your Information", data: {tooltip: true} %><br/>
    <%= f.datetime_select :starts_at %>
  </p>
   <p>
    <%= f.label :image_file_name, title: "Enter Your Information", data: {tooltip: true} %><br/>
    <%= f.text_field :image_file_name, size: 30,
    placeholder: "Gif, JPG, or PNG file name" %>
  </p>
   <p>
   <%= f.label :capacity, title: "Enter Your Information", data: {tooltip: true} %><br/>
   <%= f.number_field :capacity %>
  </p>
    <ul-class "button-group">
    <%= f.submit 'Add Event', :class => 'button' %>
    <%= link_to "Cancel", events_path, class: "button", :method => :get %></ul>
<% end %>

app/views/events/edit.html.erb
<h1>Editing <%= @event.name %></h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1><%= pluralize(@events.size, 'Event') %> Coming Soon!</h1>


<% @events.each do |event| %>
  <article>
    <header>
      <h2><%= link_to(event.name, event) %></h2>
      <%= image_for(event) %>
      <br>
    </header>
      <br>
      <p>
        <%= truncate(event.description, length: 120, seperator: ' ') %>
      </p>
      <h4><%= register_link_for(event) %></h4>
      <table>
        <tr>
          <th>When:</th>
          <td><%= event.starts_at %></td>
        </tr>
        <tr>
          <th>Where:</th>
          <td><%= event.location %><td>
        </tr>
        <tr>
          <th>Price:</th>
          <td><%= format_price(event) %></td>
        </tr>
      </table>
      <hr>
  </article>
<% end %>

app/views/events/new.html.erb
<h1>Add New Event</h1>
<h4>Please provide the information we need to add your event to our list. Image upload capability coming soon- Please leave blank for now, and a default image will be used. Make sure that your event happens in the future, not the past. I'm still looking for a Time-Travel gem.</h4>
<%= render 'form' %>

app/views/events/show.html.erb
<div>
  <%= image_for(@event) %>
</div>

<article>
    <header>
      <h2><%= @event.name %></h2>
      <h4><%= register_link_for(@event) %></h4>
    </header>
      <p>
        <%= @event.description %>
        <h4><%= link_to "Show Registrations", event_registrations_path(@event) %></h4>
      </p>
      <hr>
      <strong>When:</strong>
      <br>
      <p><%= @event.starts_at %></p>
      <hr>
      <strong>Where: </strong>
      <br>
      <p><%= @event.location %></p>
      <hr>
      <strong>Price: </strong>
      <br>
      <p><%= format_price(@event) %></p>
</article>

<!-- Disabled by JW --!> 

  
<!-- <div>
<ul-class "button-group">
<%= link_to "See All Events", root_path, class: 'small button', :method => :get %>
<%= link_to "Edit", edit_event_path(@event), :class => 'small button', :method => :get %>
<%= link_to "Delete", event_path(@event), :class => 'small button', method: :delete, data: {confirm: 'Are you sure?'} %>
</ul>
</div> -->

app/views/info/about.html.erb
<br>
  <div class="row">
    <div class="large-12 columns">
      <img src="http://pnthr.com/wp-content/uploads/2013/08/github.gif">

      <hr>
    </div>
  </div>
  

  <div class="row">
    <div class="large-12 columns">
      <h4>Welcome to GeekSocial.</h4>

      <p>So you've found your way to GeekSocial, eh? Great! Thanks for swinging by. I made this site because I wanted a place to show off Rails web design. This particular app has an Event model and a Registration model, with a User model courtesy of Devise. The Event model has_many :registrations and the Registration model belongs_to :event. Most of the logic takes place in the Event controller, with a few methods in the Events Helper as well. (The method that displays the "Sold Out" image for the Rails Hackathon rather than a registration button on the Events Index page resides there.)</p>


      <%= link_to image_tag("lettert.png"), :class => 't' %><br><br><p>he landing page (<%= link_to "with the MacBook and iPhone on the wooden table", root_path %>) was created with a Twitter Bootstrap CDN- I overrode the application html and css files in the controller for that particular static page and imported the Bootstrap stylesheets thanks to the CDN. From there I built a minimalistic landing page with a creative commons background image from Unsplash. This fully responsive demonstration Ruby on Rails app features complete user authentication functionality via Twitter-Oauth and the Devise Rails gems. I designed and built the site in Rails 4 with Ruby v1.9.3, while under version control at GitHub. The rest of the front-end (Sans the Bootstrap landing page) was built on the Foundation 4 framework. Google Analytics is installed and reporting <a href="http://railsapps.github.io/rails-google-analytics.html">thanks to the Rails 4 Turbolinks workaround.</a> Typography comes courtesy of Google Fonts- Specifically, the 'Ubuntu' font for the headers and 'Dosis' for the body text. They had to be called through an HTML link in the _header partial because apparently Google Fonts in Rails 4 don't like to render once deployed to Heroku when imported through @importcss.</p>

      <p><a href="http://shrouded-ravine-2465.herokuapp.com/">Click here to see my Reddit on Rails 4/Foundation project</a>, and <a href="http://guarded-ravine-6386.herokuapp.com/">click here to see my Social Network on Rails and Bootstrap.</a></p>

      <p>Again, thanks for stopping by, and feel free to create an account to see the site in its entirety.</p>

    </div>
  </div>

app/views/info/contact.html.erb
<h1>Hire me</h1>
<h5>Hover over the image or swipe on a mobile device.</h5>

<div class="card">
  <div class="container">
    <div class="front">
      <img src="http://pnthr.com/wp-content/uploads/2013/09/jwprofilepic.jpg" />
    </div>

    <div class="back">
      <h5>Hi. Thanks for checking out my Rails demo site.</h5>
      <p>I'm currently visiting family down south, but will be looking to start a Full Stack jr Ruby on Rails developer job back in Boston towards the end of October. I absolutely love the Rails framework and will be making a long career out of it~ I have a passion for the web, love to make beautiful and solid technology products, and endevour every day to be the best engineer and designer that I can be.</p>
      <p><a href="http://guarded-ravine-6386.herokuapp.com/">Click here to see my "Social Network" on Rails demo, </a>and <a href="http://shrouded-ravine-2465.herokuapp.com/">click here to see my Reddit on Rails demo.</a> You can contact me <a href="mailto: Jesse.Waites@Gmail.com">here at my email address</a>, and you can <a href="https://www.dropbox.com/s/vildj9d3a43o4bw/Jesse%20Waites%20Rails%20Resume.docx">download my resume here.</a></p>
      <%= image_tag("thanks2.png") %>
    </div>
  </div>
</div>

app/views/info/landing.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>GeekSocial</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet" />



    <link href="http://fonts.googleapis.com/css?family=Abel|Open+Sans:400,600" rel="stylesheet" />

    <style>

        /* http://css-tricks.com/perfect-full-page-background-image/ */
        html {
            background: url(http://pnthr.com/wp-content/uploads/2013/09/work-stations-plus-espresso.jpg) no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }



        body {
            padding-top: 20px;
            font-size: 16px;
            font-family: "Open Sans",serif;
            background: transparent;
        }

        h1 {
            font-family: "Abel", Arial, sans-serif;
            font-weight: 400;
            font-size: 40px;
        }

        /* Override B3 .panel adding a subtly transparent background */
        .panel {
            background-color: rgba(255, 255, 255, 0.5);
        }

        .margin-base-vertical {
            margin: 40px 0;
        }

        .btn-success {
color: #fff;
background-color: #860E0E;
border-color: #FFFFFF;
}


    </style>

</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-offset-3 panel">
                <div class="text-center">
                <h1 class="margin-base-vertical">Welcome to GeekSocial.</h1>

                <p>
                    GeekSocial is a demonstration Ruby on Rails 4 site from Jesse Waites.
                </p>
                <p>
                    Have a look around, read the "About" page to learn about the technology stack, or create an account to register for an event or list an event yourself.
                </p>

                <p>
                    Thanks for stopping by.
                </p>
                </div>

                    <p class="text-center">
                        <%= link_to "Enter GeekSocial", events_path, class: "btn btn-success btn-large" %>

                    </p>
                    </span>
            </div><!-- //main content -->
        </div><!-- //row -->
    </div> <!-- //container -->

</body>
<%= render 'layouts/ga' %>
</html>

app/views/info/test.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>GeekSocial</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet" />



    <link href="http://fonts.googleapis.com/css?family=Abel|Open+Sans:400,600" rel="stylesheet" />

    <style>

        /* http://css-tricks.com/perfect-full-page-background-image/ */
        html {
            background: url(http://pnthr.com/wp-content/uploads/2013/09/network2.jpg) no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }



        body {
            padding-top: 20px;
            font-size: 16px;
            font-family: "Open Sans",serif;
            background: transparent;
        }

        h1 {
            font-family: "Abel", Arial, sans-serif;
            font-weight: 400;
            font-size: 40px;
        }

        /* Override B3 .panel adding a subtly transparent background */
        .panel {
            background-color: rgba(255, 255, 255, 0.5);
        }

        .margin-base-vertical {
            margin: 40px 0;
        }

        .btn-success {
color: #fff;
background-color: #860E0E;
border-color: #FFFFFF;
margin-top: 84px;
}


    </style>

</head>
<body>
<div class="row text-center">
<%= link_to image_tag("addfriend.png"), events_path %>
</div>



                    </span>
            </div><!-- //main content -->
        </div><!-- //row -->
    </div> <!-- //container -->

</body>

</html>

app/views/layouts/_footer.html.erb
<div class="container">
<div class="row-fluid">
        <div class="span12">

        </div>
      </div>
      <hr>
      <div class="row-fluid">
        <div class="span12">
          <div class="span8">
            <a href="#">Terms of Service</a>
            <a href="#">Privacy</a>
            <a href="#">Security</a>
          </div>
          <div class="span4">
            <p class="muted pull-right">© 2013 Company Name. All rights reserved</p>
          </div>
        </div>
      </div>
  </div>
  <br>
  <br>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43688887-1', 'herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Demo Ruby on Rails 4 site" %></title>

    <%= stylesheet_link_tag    "application" %>
    <script src="/js/custom.modernizr.js"></script>
    <%= csrf_meta_tags %>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
  <script>!window.jQuery && document.write('<script src="jquery-1.4.1.min.js"><\/script>')</script>
  
  <!-- The raptorize file  -->
  <script src="jquery.raptorize.1.0.js"></script>
  
  <!-- For the button version -->
  <script type="text/javascript">
    $(window).load(function() {
      $('.button').raptorize();
    });
  </script>

  </head>

  <body>
    <div class="contain-to-grid sticky">
     <nav class="top-bar">
  <ul class="title-area">
    <li class="name", "toggle-topbar menu-icon">
      <h1><%= link_to "GeekSocial", events_path %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Browse Events", events_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Add Event", new_event_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Hire Me", info_contact_path %></li>
      <li class="divider"></li>
      <li><%= link_to "About", info_about_path %></li>
      <li class="divider"></li>
      <li class="has-dropdown"><a href="#">Account</a>
          <ul class="dropdown">
          <li class="has-dropdown"><%= link_to "Sign Up", new_user_registration_path %>
          <li class="has-dropdown"><%= link_to "Sign In", new_user_session_path %>
          <li class="has-dropdown"><%= link_to "Sign Out", destroy_user_session_path %>
    </ul>
  </div>
  </div>
</div>
</nav>

<div class="row">
  <div class="large-8 columns">
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#" name="top">Event Calendar +</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><a href="#"><i class="icon-home"></i> Home</a></li>
          <li class="divider-vertical"></li>
          <li class="active"><a href="#"><i class="icon-file"></i> Pages</a></li>
          <li class="divider-vertical"></li>
          <li><a href="#"><i class="icon-envelope"></i> Messages</a></li>
          <li class="divider-vertical"></li>
                    <li><a href="#"><i class="icon-signal"></i> Stats</a></li>
          <li class="divider-vertical"></li>
          <li><a href="#"><i class="icon-lock"></i> Permissions</a></li>
          <li class="divider-vertical"></li>
        </ul>
        <ul class="nav pull-right">
          <li><a href="/signup">Sign Up</a></li>
                    <li class="divider-vertical"></li>
          <li class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In <strong class="caret"></strong></a>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
              <form method="post" action="login" accept-charset="UTF-8">
                <input style="margin-bottom: 15px;" type="text" placeholder="Username" id="username" name="username">
                <input style="margin-bottom: 15px;" type="password" placeholder="Password" id="password" name="password">
                <input style="float: left; margin-right: 10px;" type="checkbox" name="remember-me" id="remember-me" value="1">
                <label class="string optional" for="user_remember_me"> Remember me</label>
                <input class="btn btn-primary btn-block" type="submit" id="sign-in" value="Sign In">
                <label style="text-align:center;margin-top:5px">or</label>
                                <input class="btn btn-primary btn-block" type="button" id="sign-in-google" value="Sign In with Google">
                <input class="btn btn-primary btn-block" type="button" id="sign-in-twitter" value="Sign In with Twitter">
              </form>
            </div>
          </li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
    <!--/.container-fluid -->
  </div>
  <!--/.navbar-inner -->
</div>
<!--/.navbar -->

<script>
$(document).ready(function()
{
  //Handles menu drop down
  $('.dropdown-menu').find('form').click(function (e) {
        e.stopPropagation();
        });
  });
</script>

app/views/layouts/_sideandfooter.html.erb
</div>
  <div class="large-4 columns"><br>
    <% if user_signed_in? %>
        Logged in as:<p><%= current_user.name %></p>
        <% end %>
    <h2 class="subheader">What Is This?</h2>
    <hr>
    GeekSocial is a fully responsive demonstration Ruby on Rails app and event calendar for smart people. GeekSocial features complete user authentication functionality via the Twitter-Oauth and Devise gems. Site design and implementation by Jesse Waites in Rails 4.0, with Ruby v1.9.3, while under version control at GitHub. The front-end was built on the Foundation 4 framework. Google Analytics is installed and reporting. Typography comes courtesy of Google Fonts- Specifically, the 'Ubuntu' font for the headers and 'Dosis' for the body text. The color scheme was selected by my little sister and I. She was compensated for her consulting services with Ice cream.
    <hr>
    <%= link_to image_tag("connecttwitter.png"), new_user_registration_path %>
    <hr>
    <br>
    <%= link_to image_tag("hireme.png"), "http://fierce-badlands-2327.herokuapp.com/info/contact" %>
  </div>


</div>

<footer class="row">
    <div class="large-12 columns">
      <hr>
      <div class="row">
        <div class="large-6 columns">
          <p>Built by Jesse Waites with Rails 4 & Foundation 4</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="http://www.linkedin.com/profile/view?id=69029327">LinkedIn</a></li>
            <li><a href="https://github.com/piratebroadcast/">Github</a></li>
          </ul>
        </div>
      </div>
    </div>
    <%= render 'layouts/ga' %>
  </footer>
    <link href='http://fonts.googleapis.com/css?family=Dosis:400,500|Ubuntu' rel='stylesheet' type='text/css'>
  </body>
</html>

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>

    <%= yield %>

<%= render 'layouts/sideandfooter' %>

app/views/pages/about.html.erb
about.html.erb